using BaseLib.Utils;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.CardPools;
using RunePriest.RunePriestCode.Runes;

namespace RunePriest.RunePriestCode.Cards.Status;

/// <summary>Status: when drawn, Inscribe Mirror. Generated by reckless Rune Priest cards.</summary>
[Pool(typeof(StatusCardPool))]
public sealed class SmudgedGlyph() : RunePriestCard(-1, CardType.Status, CardRarity.Status, TargetType.None)
{
    public override int MaxUpgradeLevel => 0;
    public override bool CanBeGeneratedInCombat => false;
    public override IEnumerable<CardKeyword> CanonicalKeywords => [CardKeyword.Unplayable, CardKeyword.Ethereal];

    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
        [RuneTips.Inscribe, ..new TargetRune(TargetMode.Mirror).HoverTips];

    public override async Task AfterCardDrawn(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw)
    {
        if (card != this) return;
        await RuneCmd.Inscribe(choiceContext, Owner, [Glyph.Of(new TargetRune(TargetMode.Mirror))], this);
    }
}
